import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
	ADROUTER_CATALOG_PATH,
	computeAdRouterCatalogDigest,
	parseAdRouterCatalog,
	validateAdRouterCatalog,
} from "../packages/ai/scripts/adrouter-catalog.ts";

const catalog = parseAdRouterCatalog(readFileSync(ADROUTER_CATALOG_PATH));

function withDigest(candidate) {
	return {
		...candidate,
		catalog_digest: computeAdRouterCatalogDigest({
			schema_version: candidate.schema_version,
			models: candidate.models,
		}),
	};
}

function expectInvalid(mutator, pattern = /invalid_adrouter_catalog/) {
	const candidate = structuredClone(catalog);
	mutator(candidate);
	assert.throws(() => validateAdRouterCatalog(candidate), pattern);
}

test("accepts the committed Router catalog", () => {
	assert.equal(catalog.models.length, 8);
	assert.equal(catalog.models[0].id, "deepseek-v4-flash");
	assert.equal(catalog.models[7].id, "agnes-2.5-pro-alpha");
});

test("rejects schema, digest, and key drift", () => {
	expectInvalid((candidate) => {
		candidate.schema_version = 2;
	});
	expectInvalid((candidate) => {
		candidate.catalog_digest = `sha256:${"0".repeat(64)}`;
	});
	expectInvalid((candidate) => {
		candidate.extra = true;
	});
	expectInvalid((candidate) => {
		candidate.models[0].configured = true;
	});
});

test("rejects model order, identity, class, limits, and thinking drift even with a valid digest", () => {
	for (const mutate of [
		(candidate) => candidate.models.reverse(),
		(candidate) => (candidate.models[0].id = candidate.models[1].id),
		(candidate) => (candidate.models[0].provider = "qwen"),
		(candidate) => (candidate.models[0].model_class = "frontier"),
		(candidate) => (candidate.models[0].max_output_tokens = 8192),
		(candidate) => (candidate.models[0].thinking_levels = ["none", "high"]),
		(candidate) => (candidate.models[0].default_thinking_level = "high"),
	]) {
		expectInvalid((candidate) => Object.assign(candidate, withDigest(mutateAndReturn(candidate, mutate))));
	}
});

test("invalid synchronization input leaves vendored and generated bytes unchanged", () => {
	const directory = mkdtempSync(join(tmpdir(), "adrouter-invalid-catalog-"));
	const source = join(directory, "invalid.json");
	const generatedPath = "packages/ai/src/providers/adrouter.models.ts";
	const vendorBefore = readFileSync(ADROUTER_CATALOG_PATH);
	const generatedBefore = readFileSync(generatedPath);
	try {
		const invalid = structuredClone(catalog);
		invalid.models[0].max_output_tokens = -1;
		invalid.catalog_digest = computeAdRouterCatalogDigest({
			schema_version: invalid.schema_version,
			models: invalid.models,
		});
		writeFileSync(source, JSON.stringify(invalid));
		const result = spawnSync(process.execPath, ["scripts/sync-adrouter-catalog.mjs", "--source", source], {
			encoding: "utf8",
		});
		assert.notEqual(result.status, 0);
		assert.deepEqual(readFileSync(ADROUTER_CATALOG_PATH), vendorBefore);
		assert.deepEqual(readFileSync(generatedPath), generatedBefore);
	} finally {
		rmSync(directory, { recursive: true, force: true });
	}
});

function mutateAndReturn(candidate, mutate) {
	mutate(candidate);
	return candidate;
}
