// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const ADROUTER_MODELS = {
	"deepseek-v4-flash": {
		id: "deepseek-v4-flash",
		name: "AdRouter DeepSeek V4 Flash",
		api: "adrouter-agent",
		provider: "adrouter",
		baseUrl: "",
		reasoning: true,
		thinkingLevelMap: {"off":"none","minimal":null,"low":null,"medium":"medium","high":"high","xhigh":null,"max":null},
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 4096,
	} satisfies Model<"adrouter-agent">,
	"deepseek-v4-pro": {
		id: "deepseek-v4-pro",
		name: "AdRouter DeepSeek V4 Pro",
		api: "adrouter-agent",
		provider: "adrouter",
		baseUrl: "",
		reasoning: true,
		thinkingLevelMap: {"off":"none","minimal":null,"low":null,"medium":"medium","high":"high","xhigh":null,"max":null},
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 4096,
	} satisfies Model<"adrouter-agent">,
} as const;
